:sparkles: ad a method to exist if one entity exist with
Troopers/BehatContexts pull request #19
Opened 2017-03-09 15:15 UTC by Charlie-Lucas

2017-03-09 16:19 UTC, alexisLefebvre approved these changes

2017-03-09 16:40 UTC, lenybernard commented
please consider implementing the inverse method `I should not find a User with lastname Abitbol`

2017-03-09 16:44 UTC, lenybernard commented on src/Troopers/BehatContexts/Context/ExtendedEntityContext.php
> +            throw new \Exception(sprintf('There is not any object for the following params: %s', json_encode($this->getQueryParams($entityName, $headers, $row))));
What is it supposed to echo ? Something like this I guess :
```
There is not any object for the following params: {"firstname":"Abitlabol","enabled":false}
```

I guess we could be more pretty 💋  but it's ok for developers

2017-03-09 16:45 UTC, lenybernard requested changes
please consider implementing the inverse method:
```
Then I should not find one User like:
      | lastname |
      | Abitbol  |
```

2017-03-09 16:48 UTC, lenybernard requested changes
Please add a quantity variable instead of `one`,  We could be interested to find X users with lastname abitbol

2017-03-09 21:13 UTC, alexislefebvre commented on src/Troopers/BehatContexts/Context/ExtendedEntityContext.php
> +        $entityName = $this->resolveEntity($name)->getName();
The code from `$entityName` to `$this->getQueryParams($entityName, $headers, $row);` is duplicated, can you please factorize it in a method?

2017-03-09 21:14 UTC, alexislefebvre commented on src/Troopers/BehatContexts/Context/ExtendedEntityContext.php
> +            throw new \Exception(sprintf('There is not any %s for the following params: %s', $name, json_encode($this->getQueryParams($entityName, $headers, $row))));
`$this->getQueryParams($entityName, $headers, $row)` is called 3 times in this method, a variable may be used to store this data.

2017-03-10 13:15 UTC, lenybernard approved these changes

2017-03-10 13:44 UTC, merged